services:
    postgres:
        image: postgres:17

        container_name: wmp-postgres

        restart: unless-stopped

        env_file:
            -   .env

        ports:
            -   "15432:5432"

        volumes:
            -   postgres-data:/var/lib/postgresql/data
            -   ../docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

        networks:
            -   wmp-network

    minio:
        image: minio/minio:RELEASE.2025-07-23T15-54-02Z

        container_name: wmp-minio

        restart: unless-stopped

        env_file:
            -   .env

        command: server /data --console-address ":9001"

        ports:
            -   "9000:9000"
            -   "9001:9001"

        volumes:
            -   minio-data:/data

        networks:
            -   wmp-network

volumes:
    postgres-data:

    minio-data:


networks:

    wmp-network:
        driver: bridge
