spring:
    datasource:
        url: jdbc:postgresql://localhost:15432/mail_db
        username: wmp
        password: wmp

logging:
    level:
        root: INFO

mail:
    imap:
        host: imap.mail.ru
        port: 993
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        folder: INBOX
        ssl: true
